# Generated by Django 4.2.3 on 2023-10-23 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('servicios', models.TextField()),
                ('correo', models.CharField(max_length=100)),
                ('contrasenia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GymEspacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=100)),
                ('entrenadores', models.ManyToManyField(related_name='gimnasios', to='gymapp.entrenador')),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('zona_muscular', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('enlace_tutorial', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GymUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
                ('fecha_inscripcion', models.DateField()),
                ('contrasenia', models.CharField(max_length=100)),
                ('peso', models.CharField(max_length=10)),
                ('altura', models.CharField(max_length=10)),
                ('gymespacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.gymespacio')),
            ],
        ),
        migrations.AddField(
            model_name='gymespacio',
            name='maquinas',
            field=models.ManyToManyField(to='gymapp.maquina'),
        ),
        migrations.AddField(
            model_name='entrenador',
            name='gymespacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.gymespacio'),
        ),
    ]
