# Generated by Django 4.2.3 on 2023-10-30 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('zona_muscular', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('enlace_tutorial', models.URLField()),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
                ('contrasenia', models.CharField(max_length=25)),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='GymEspacio',
            fields=[
                ('usuariopadre_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gymapp.usuariopadre')),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('maquinas', models.ManyToManyField(to='gymapp.maquina')),
            ],
            bases=('gymapp.usuariopadre',),
        ),
        migrations.CreateModel(
            name='GymUser',
            fields=[
                ('usuariopadre_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gymapp.usuariopadre')),
                ('fecha_inscripcion', models.DateField()),
                ('peso', models.CharField(blank=True, max_length=10, null=True)),
                ('altura', models.CharField(blank=True, max_length=10, null=True)),
                ('id_gymespacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.gymespacio')),
            ],
            bases=('gymapp.usuariopadre',),
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('usuariopadre_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gymapp.usuariopadre')),
                ('servicios', models.TextField()),
                ('id_gymespacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.gymespacio')),
            ],
            bases=('gymapp.usuariopadre',),
        ),
    ]
