# Generated by Django 4.2.3 on 2023-11-12 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaMuscular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='maquina',
            name='id_zonamuscular',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gymapp.zonamuscular'),
            preserve_default=False,
        ),
    ]
