# Generated by Django 4.2.3 on 2023-10-24 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0002_gymespacio_contrasenia_alter_gymespacio_entrenadores'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='entrenador',
            old_name='gymespacio',
            new_name='id_gymespacio',
        ),
        migrations.RenameField(
            model_name='gymuser',
            old_name='gymespacio',
            new_name='id_gymespacio',
        ),
        migrations.RemoveField(
            model_name='gymespacio',
            name='entrenadores',
        ),
        migrations.AddField(
            model_name='maquina',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='entrenador',
            name='id_tipo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gymapp.tipousuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gymespacio',
            name='id_tipo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gymapp.tipousuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gymuser',
            name='id_tipo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gymapp.tipousuario'),
            preserve_default=False,
        ),
    ]
