# Generated by Django 4.2.3 on 2023-11-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0004_maquina_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymespacio',
            name='maquinas',
            field=models.ManyToManyField(blank=True, null=True, to='gymapp.maquina'),
        ),
    ]
