# Generated by Django 4.2.3 on 2023-11-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0005_alter_gymespacio_maquinas'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='foto_perfil',
            field=models.ImageField(default=0, upload_to='imagenesEntrenador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrenador',
            name='precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gymuser',
            name='foto_perfil',
            field=models.ImageField(default=0, upload_to='imagenesUsuario'),
            preserve_default=False,
        ),
    ]
