# Generated by Django 4.2.3 on 2023-10-25 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0006_alter_gymuser_altura_alter_gymuser_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='id_tipo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='gymapp.tipousuario'),
        ),
    ]
