# Generated by Django 4.2.3 on 2023-10-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0007_maquina_qr_code_alter_entrenador_id_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='enlace_tutorial',
            field=models.URLField(),
        ),
    ]
