# Generated by Django 4.2.3 on 2023-10-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0008_alter_maquina_enlace_tutorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='static/qr_codes'),
        ),
    ]
