# Generated by Django 4.2.3 on 2023-11-27 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0009_tenant_tenantawaremodel_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantawaremodel',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
        migrations.DeleteModel(
            name='TenantAwareModel',
        ),
    ]
