# Generated by Django 4.2.3 on 2023-10-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0013_alter_maquina_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
    ]
